# Generated by Django 5.1.1 on 2024-09-10 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=250)),
                ('holder', models.CharField(max_length=600, verbose_name='Titular de la tarjeta')),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=56)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=56)),
                ('issue_date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='banco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
