# Generated by Django 5.1.1 on 2024-09-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_options_bank_deleted_at_alter_bank_logo'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Tarjeta de credito', 'verbose_name_plural': 'Tarjetas de credito'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='created',
        ),
        migrations.AddField(
            model_name='card',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=250, verbose_name='Número de tarjeta.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Límite de credito'),
        ),
        migrations.AlterField(
            model_name='card',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo actua'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(verbose_name='Fecha de expiracion'),
        ),
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateField(verbose_name='Fecha de emision'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(max_length=56, verbose_name='Estado de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=56, verbose_name='Tipo de tarjeta'),
        ),
    ]
