# Generated by Django 5.1.1 on 2024-09-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_options_remove_card_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Límite de credito'),
        ),
        migrations.AlterField(
            model_name='card',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo actua'),
        ),
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emision'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Estado de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Tipo de tarjeta'),
        ),
    ]
