# Generated by Django 5.1.1 on 2024-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=8, verbose_name='Fecha de expiracion'),
        ),
    ]
