# Generated by Django 5.1.1 on 2024-09-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='card',
            name='issue_date',
        ),
    ]
