# Generated by Django 5.1.1 on 2024-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_credit_limit_remove_card_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Número de tarjeta.'),
        ),
    ]
