# Generated by Django 5.1.1 on 2024-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AddField(
            model_name='bank',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.URLField(verbose_name='Url Logo'),
        ),
    ]
