# Generated by Django 5.1.1 on 2024-09-19 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Limite')),
                ('period_length', models.PositiveIntegerField(default=7, verbose_name='Frecuencia dia')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('banco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bank.bank', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Configacion de frecuencia',
                'verbose_name_plural': 'Configacion de frecuencias',
            },
        ),
    ]
