# Generated by Django 5.1.1 on 2024-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='config',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
    ]
