# Generated by Django 5.1.1 on 2024-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_config_end_date_alter_config_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='period_length',
        ),
        migrations.AddField(
            model_name='config',
            name='period',
            field=models.CharField(choices=[('W', 'Semanal'), ('B', 'Quincenal'), ('M', 'Mensual')], default='W', max_length=2, verbose_name='Frecuencia dia'),
        ),
    ]
