# Generated by Django 5.1.1 on 2024-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_config_period_length_config_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='bank',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Limite'),
        ),
        migrations.AddField(
            model_name='bank',
            name='period',
            field=models.CharField(choices=[('W', 'Semanal'), ('B', 'Quincenal'), ('M', 'Mensual')], default='W', max_length=2, verbose_name='Frecuencia dia'),
        ),
        migrations.AddField(
            model_name='bank',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
