# Generated by Django 5.1.1 on 2024-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bank_end_date_bank_limit_amount_bank_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Limite'),
        ),
    ]
