# Generated by Django 5.1.1 on 2024-09-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_bank_limit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Url Logo'),
        ),
    ]
